vscode:
  extensions:
    - dracula-theme.theme-dracula@2.18.1:XgpbxhhUSPGI4YfNBYpr1A==
    - esbenp.prettier-vscode@3.8.0:IFNUDOjinxu7cO/8zYtZIw==
    - PKief.material-icon-theme@3.9.1:g1O+jL+iaYZp5mMmzpPEug==
    - Mikael.Angular-BeastCode@8.0.10:J7aGjVXXDeyuqnhsk+vMYw==